apostas_boloes/adesao/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('apostas_boloes.adesao.views',
    url(r'^$', 'adesao', name='adesao'),
)

apostas_boloes/apostas/urls.py
from django.conf.urls import patterns, include, url
from apostas_boloes import apostas


urlpatterns = patterns('apostas_boloes.apostas.views',
    url(r'^apostasLoteria$', 'apostas_loteria', name='apostas_loteria'),
    url(r'^apostar_loteria/(\d+)/$', 'apostar_loteria', name='apostar_loteria'),
    url(r'^apostasBolao$', 'apostas_bolao', name='apostas_bolao'),
    url(r'^apostar_bolao/(\d+)/$', 'apostar_bolao', name='apostar_bolao'),
    url(r'^minhas_apostas', 'minhas_apostas', name='minhas_apostas'),
)

apostas_boloes/core/urls.py
from django.conf.urls import patterns, include, url
from apostas_boloes import core


urlpatterns = patterns('apostas_boloes.core.views',
	url(r'^$', 'home', name='home'),
	url(r'^login$', 'login' , name='login'),
	url(r'^logout$', 'logout', name='logout')
)

apostas_boloes/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^adesao/', include('apostas_boloes.adesao.urls', namespace='adesao')),
    url(r'', include('apostas_boloes.core.urls', namespace='core')),
    url(r'^apostas/', include('apostas_boloes.apostas.urls', namespace='apostas')),
)

apostas_boloes/core/models.py
from django.db import models

# Create your models here.

apostas_boloes/core/views.py
from django.contrib import auth
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse


def home(request):
	return render(request, 'core/home.html')


def login(request): 
	if request.method == 'POST':		
		username = request.POST['username']
		password = request.POST['password']
		user = auth.authenticate(username=username, password=password)
		if user is not None:
			auth.login(request, user)
			print request.GET
			if request.POST.has_key('next'):
				return HttpResponseRedirect(request.POST['next'])
			return HttpResponseRedirect(reverse('core:home'))
		else:
			return render(request, 'login.html',{'error': True})
	return render(request, 'login.html', request.GET)

def logout(request):
	auth.logout(request)
	return HttpResponseRedirect(reverse('core:home'))

apostas_boloes/core/templates/base.html
{% load bootstrap_toolkit %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        Sistema de Apostas e Bolões{% block title %}{% endblock %}        
	</title>
	<meta name="description" content="Projeto Adesão">
    <meta name="author" content="Élysson MR">
    {% bootstrap_stylesheet_tag %}
    {% bootstrap_stylesheet_tag "responsive" %}
    <style type="text/css">
    </style>
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    {% bootstrap_javascript_tag %}
    {% block extra_head %}{% endblock %}
</head>
<body>
	<div class="container well well-small" id="header">
		<div id="navigation" class="navbar navbar-static-top">
            <div class="navbar-inner">
                <a class="brand" href="{% url 'core:home' %}">Apostas e Bolões</a>
                <ul class="nav">
                    {% if not user.is_authenticated %}
                    <li>
                        <a href="{% url 'adesao:adesao' %}">Adesão</a>
                    </li>
                    {% endif %}
                    <li class="dropdown">
                        <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                            Apostas
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                            <li role="presentation">
                                <a href="{% url 'apostas:apostas_loteria' %}">
                                    Apostas Loteria
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="{% url 'apostas:apostas_bolao' %}">Bolões</a>
                            </li>
                            <li role="presentation">
                                <a href="{% url 'apostas:minhas_apostas' %}">Minhas Apostas</a>
                            </li>
                        </ul>
                    </li>
                    {% if user.is_staff %}
                    <li>
                        <a href="{% url 'admin:index' %}">Administração</a>
                    </li>
                    {% endif %}
                </ul>
                {% if not user.is_authenticated %}
                <div class="btn-group pull-right">
                    <a href="{% url 'core:login' %}" class="btn btn-primary pull-right">
                    Acesso
                    </a>
                </div>
                
                {% else %}
                <div class="btn-group pull-right">
                    <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <i class="icon white user"></i>
                        {{ user.username }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'core:logout' %}">
                                <i class="icon-off"></i>
                                Sair
                                 
                            </a>
                        </li>
                    </ul>
                </div>        
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container well" id="content">
        {% if msg %}
        <div class="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p>
                {{ msg }}
            </p>
        </div>
        {% endif %}
		{% block content %}
		{% endblock %}
    </div>

    <div id="footer" class="container well well-small">
        <p>Sistema de Apostas e Bolões. A melhor maneira de organizar as apostas entre os seus amigos!</p>
    </div>
</body>
</html>

apostas_boloes/core/templates/login.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block title %}
 - Acesso
{% endblock %}

{% block content %}
<div class="row">
	<div class="span4 offset4 well">
		<legend>Acesso ao Sistema de Apostas</legend>
      	{% if error %}
      	<div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">×</a>Usuário e/ou senha Incorreto(s)!
        </div>
        {% endif %}
		<form method="POST" action="{% url 'core:login' %}" >
			{% csrf_token %}
			<input type="hidden" name="next" id="next" value="{{ next }}"/>
			<input type="text" id="username" class="span4" name="username" placeholder="Usuário">
			<input type="password" id="password" class="span4" name="password" placeholder="Senha">
			<button type="submit" name="submit" class="btn btn-info btn-block">Acessar</button>
		</form>    
	</div>
</div>
{% endblock %}