apostas_boloes/apostas/urls.py
from django.conf.urls import patterns, include, url
from apostas_boloes import apostas


urlpatterns = patterns('apostas_boloes.apostas.views',
    url(r'^apostasLoteria$', 'apostas_loteria', name='apostas_loteria'),
    url(r'^apostar_loteria/(\d+)/$', 'apostar_loteria', name='apostar_loteria'),
    url(r'^apostasBolao$', 'apostas_bolao', name='apostas_bolao'),
    url(r'^apostar_bolao/(\d+)/$', 'apostar_bolao', name='apostar_bolao'),
    url(r'^minhas_apostas', 'minhas_apostas', name='minhas_apostas'),
)

apostas_boloes/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^adesao/', include('apostas_boloes.adesao.urls', namespace='adesao')),
    url(r'', include('apostas_boloes.core.urls', namespace='core')),
    url(r'^apostas/', include('apostas_boloes.apostas.urls', namespace='apostas')),
)

apostas_boloes/apostas/models.py
# coding: utf-8
from django.db import models
from apostas_boloes.adesao.models import Participante

class Jogo(models.Model):
	pago = models.BooleanField('Já Pagou?', default=False)
	participante = models.ForeignKey(Participante)	
	#data_pagamento = models.DateField('Data Pagamento')
	
	class Meta:
		abstract = True			

class JogoLoteria(Jogo):
	aposta = models.ForeignKey('ApostaLoteria')

	def __unicode__(self):
		return '%s apostou %.2f em %s' % \
		(self.participante.nome, self.aposta.valor, self.aposta.nome)

	class Meta:
		verbose_name = 'Jogo Loteria'
		verbose_name_plural = 'Jogos Loteria'
			

class JogoBolao(Jogo):
	aposta = models.ForeignKey('ApostaBolao')
	gols_timeA = models.PositiveSmallIntegerField('TimeA', default=0)
	gols_timeB = models.PositiveSmallIntegerField('TimeB', default=0)

	def __unicode__(self):
		return '%s aposto %d gols no %s e %d gols no %s' % \
		(self.participante.nome, self.gols_timeA, self.aposta.timeA, \
			self.gols_timeB, self.aposta.timeB)

	class Meta:
		verbose_name = 'Jogo Bolão'
		verbose_name_plural = 'Jogos Bolão'
			

class Aposta(models.Model):
	nome = models.CharField('Nome', max_length=50)
	descricao = models.TextField('Descrição', max_length=100)
	valor = models.DecimalField('Valor da Aposta', max_digits=10, decimal_places=2)
	ativo = models.BooleanField('Ativado', default=True)
	data_final = models.DateField('Data Final para Apostas', blank = True)

	def __unicode__(self):
		return self.nome
	
	class Meta:
		abstract = True


class ApostaLoteria(Aposta):
	data_sorteio = models.DateField('Data Sorteio', auto_now = True)		
	participantes = models.ManyToManyField(Participante, through='JogoLoteria')

	class Meta:
		verbose_name = 'Aposta Loteria'
		verbose_name_plural = 'Apostas Loteria'
			

class ApostaBolao(Aposta):
	timeA = models.CharField('Time A', max_length=50)
	timeB = models.CharField('Time B', max_length=50)
	participantes = models.ManyToManyField(Participante, through='JogoBolao')

	def __unicode__(self):
		return '%s x %s' % (self.timeA, self.timeB)

	class Meta:
		verbose_name = 'Bolão'
		verbose_name_plural = 'Bolões'

apostas_boloes/apostas/forms.py
from django import forms
from apostas_boloes.apostas.models import JogoBolao


class JogoBolaoForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		timeA = kwargs.pop('timeA')
		timeB = kwargs.pop('timeB')
		super(JogoBolaoForm, self).__init__(*args, **kwargs)
		self.fields['gols_timeA'].label = timeA
		self.fields['gols_timeB'].label = timeB

	class Meta:
		model = JogoBolao
		exclude = ('pago', 'aposta', 'participante')

apostas_boloes/apostas/views.py
# coding: utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from apostas_boloes.apostas.forms import JogoBolaoForm
from apostas_boloes.apostas.models import ApostaLoteria, JogoLoteria, JogoBolao, ApostaBolao
from apostas_boloes.adesao.models import Participante
from datetime import datetime
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required




def apostas_loteria(request):
    # Lista as apostas válidas e coloca a opção para ousuário escolher e apostar
    
    apostas = ApostaLoteria.objects.filter(ativo=True, 
        data_final__gte=datetime.now())
    return render(request, 'apostas/apostaLoteria.html', {
        'apostas': apostas,
    })

def apostar_loteria(request, aposta_id):
    aposta = ApostaLoteria.objects.get(pk=aposta_id)
    participante = Participante.objects.get(user_id=request.user.pk)
    jogo = JogoLoteria(participante=participante, aposta=aposta)
    jogo.save()

    return HttpResponse()

def apostas_bolao(request):
    apostas = ApostaBolao.objects.filter(ativo=True, 
        data_final__gte=datetime.now())
    return render(request, 'apostas/apostaBolao.html', {
        'apostas': apostas,
    })

def apostar_bolao(request, bolao_id):
    bolao = ApostaBolao.objects.get(pk=bolao_id)
    if request.method == 'POST':
        form = JogoBolaoForm(request.POST, timeA=bolao.timeA, timeB=bolao.timeB)
        if form.is_valid():
            print form.cleaned_data
            jogo = JogoBolao()
            jogo.gols_timeA = form.cleaned_data['gols_timeA']
            jogo.gols_timeB = form.cleaned_data['gols_timeB']
            jogo.aposta = bolao
            jogo.participante = Participante.objects.get(user_id=request.user.pk)
            jogo.save()
            msg = 'Aposta no jogo "%s" Efetuada!' % bolao
            request.session['msg'] = msg
            return HttpResponseRedirect(reverse('apostas:apostas_bolao'))
    else:
        form = JogoBolaoForm(timeA=bolao.timeA, timeB=bolao.timeB) # An unbound form

    return render(request, 'apostas/apostaJogoBolao.html', {
        'form': form, 'bolao': bolao
    })

@login_required
def minhas_apostas(request):
    return HttpResponse()
    

apostas_boloes/apostas/templates/apostas/apostaBolao.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block title %}
 - Aposta Bolão
{% endblock %}


{% block content %}
<h1>Lista de Bolões Vigentes</h1>

{% if session.msg %}
    <div class="alert alert-success">
        {{ session.msg }}
    </div>
{% endif %}
<table class="table bordered-table zebra-striped table-hover">
    <thead>
        <th>Nome</th>
        <th>Valor</th>
        <th>Time A</th>
        <th>Time B</th>
        <th>Data Final</th>
        <th>Apostar</th>
    </thead>
    <tbody>
        {% for aposta in apostas %}
            <tr>
                <td>{{ aposta.nome }}</td>
                <td>{{ aposta.valor }} R$</td>
                <td>{{ aposta.timeA }} R$</td>
                <td>{{ aposta.timeB }} R$</td>
                <td>{{ aposta.data_final }}</td>
                <td><a href="{% url 'apostas:apostar_bolao' aposta.pk %}" class="btn btn-primary">Apostar</a></td>
            </tr>
        {% empty %}
            <tr >
                <td colspan="6">Nenhum Bolão Cadastrado</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

apostas_boloes/apostas/templates/apostas/apostaJogoBolao.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block title %}
 - Cadastrar Bolão
{% endblock %}


{% block content %}
<h1>Bolão - {{ bolao }}</h1>
<form action="{% url 'apostas:apostar_bolao' bolao.pk %}" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Apostar</button>
        <input type="reset" class="btn" value="Limpar"/>        
    </div>
</form>
{% endblock %}

apostas_boloes/apostas/templates/apostas/apostaLoteria.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}

{% block title %}
 - Aposta Loteria
{% endblock %}


{% block content %}
<h1>Lista de Apostas Vigentes</h1>

<table class="table bordered-table zebra-striped table-hover">
    <thead>
        <th>Nome</th>
        <th>Valor</th>
        <th>Data Final</th>
        <th>Apostar</th>
    </thead>
    <tbody>
        {% for aposta in apostas %}
            <tr>
                <td>{{ aposta.nome }}</td>
                <td>{{ aposta.valor }} R$</td>
                <td>{{ aposta.data_final }}</td>
                <td><a href="{% url 'apostas:apostar_loteria' aposta.pk %}" class="btn btn-primary">Apostar</a></td>
            </tr>
        {% empty %}
            <tr >
                <td colspan="4">Nenhuma Aposta Cadastrada</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}